version: '2'

services:

    navigation:
        image: navigation
        environment:
          - MYSQL_HOSTNAME=mysql
          - MYSQL_DATABASE=navigation
          - MYSQL_USER=navigation
          - MYSQL_PASSWORD=navigation
        depends_on: 
          - mysql
        restart: always
        ports: 
          - 7010:8360

    mysql:
        image: mysql:latest
        environment: 
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=navigation
          - MYSQL_USER=navigation
          - MYSQL_PASSWORD=navigation
        restart: always
        ports:
          - 37210:3306